name: tilbot
services:
  speech-recognition:
    build:
      context: .
      args:
        PORT: 8082    
    restart: unless-stopped
    environment:
      MODELNAME: "tiny"
      LANGUAGE: "nl"
      PORT: 8082
    ports:
      - 8082:8082
    volumes:
      - .:/app